services:
  securechain-depex:
    container_name: securechain-depex
    build:
      context: ..
      dockerfile: dev/Dockerfile
    volumes:
      - ../app:/app
    env_file:
      - ../app/.env
    ports:
      - '8002:8000'
    networks:
      - securechain
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 100s
      timeout: 100s
      retries: 10
      start_period: 300s

networks:
  securechain:
    name: securechain
    external: true
    driver: bridge
